export const  REQUIRED_MESSAGE = 'Required'
export const  INVALID_NAME_MESSAGE = 'Name cannot have white space(s) or special character(s).'
export const  NO_SPACES_MESSAGE = 'No spaces allowed.'
export const  NO_NUMBER_MESSAGE = 'Must be a number.'
export const  INVALID_EMAIL_MESSAGE = 'Invalid Email'